"""Initial migration

Revision ID: 461ec8e634ce
Revises: 
Create Date: 2025-03-07 18:17:28.933060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '461ec8e634ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('wwid', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wwid')
    )
    op.create_table('tool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('mac_address', sa.String(length=50), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('sub_owner_id', sa.Integer(), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('vlan', sa.String(length=50), nullable=True),
    sa.Column('pvlan', sa.String(length=50), nullable=True),
    sa.Column('os', sa.String(length=50), nullable=True),
    sa.Column('is_labelled', sa.Boolean(), nullable=True),
    sa.Column('has_local_admin', sa.Boolean(), nullable=True),
    sa.Column('wall_port', sa.String(length=50), nullable=True),
    sa.Column('switch', sa.String(length=50), nullable=True),
    sa.Column('switch_port', sa.String(length=50), nullable=True),
    sa.Column('tool_id', sa.Integer(), nullable=True),
    sa.Column('is_backed_up', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['owner.id'], ),
    sa.ForeignKeyConstraint(['sub_owner_id'], ['owner.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['tool.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device')
    op.drop_table('tool')
    op.drop_table('owner')
    op.drop_table('location')
    # ### end Alembic commands ###
